<?php

namespace Database\Seeders;

use App\Models\Agent;
use App\Models\Property;
use App\Support\LaunchListings;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    /**
     * Seed verified launch properties and apply corrections.
     */
    public function run(): void
    {
        $agent1 = Agent::where('email', 'abu.hanif@gbrel.com')->first();
        $agent2 = Agent::where('email', 'sirajum.munira@gbrel.com')->first();
        $agent3 = Agent::where('email', 'siam.talukder@gbrel.com')->first();

        // 1. Gulshan-1 15 Katha Estate
        Property::updateOrCreate(
            ['slug' => 'gulshan-1-135-6-15-katha-building'],
            [
                'title' => 'গুলশান ১, ১৩৫/৬ — ১৫ কাঠা জমি ও ২ তলা পুরাতন দালান',
                'slug' => 'gulshan-1-135-6-15-katha-building',
                'tagline' => '১৫ কাঠা জমি ও ২ তলা পুরাতন দালান | মোট মূল্য ৳ ৯০ কোটি (আলোচনা সাপেক্ষ)',
                'description' => 'গুলশান ১, ১৩৫/৬ নম্বরে ১৫ কাঠা জমিতে ২ তলা পুরাতন দালান বিক্রয়ের প্রস্তাব। ৫ জন ওয়ারিশ সূত্রে মালিক, গনিউর রহমান গং বর্তমানে অপ্রত্যাহার যোগ্য পাওয়ার বলে জমির মালিক। বাংলা ১৪৩২ সনের অনলাইন খাজনা ও ২০২৩ সালের নামজারি পরিশোধ করা আছে। সার্ভিস চার্জ ও ডকুমেন্টেশন ফি জমা দেওয়া আছে। সম্পূর্ণ নিষ্কণ্টক এবং টোটাল কাগজ-পাতি আপডেট। জমি মালিকের দখলে আছে। আর্থিক লেনদেন ব্যাংকের মাধ্যমে। রাজউক থেকে বিক্রয়ের অনুমতি প্রাপ্তি ১৫ (পনের) কার্যদিবস।',
                'address' => 'প্লট ১৩৫/৬, গুলশান-১, ঢাকা-১২১২',
                'city' => 'Dhaka',
                'state' => 'Dhaka North',
                'area_name' => 'Gulshan-1',
                'price' => 900000000,
                'price_unit' => 'মোট মূল্য ৳ ৯০ কোটি (প্রতি কাঠা ৳ ৬.০০ কোটি আলোচনা সাপেক্ষ)',
                'listing_type' => 'Sale',
                'property_type' => 'Land',
                'status' => 'Active',
                'bedrooms' => 6,
                'bathrooms' => 6,
                'balconies' => 4,
                'square_footage' => 5500,
                'land_size' => 15.0,
                'land_unit' => 'Katha',
                'parking' => 6,
                'floor_number' => 1,
                'total_floors' => 2,
                'facing' => 'South',
                'completion_status' => 'Ready',
                'year_built' => 1998,
                'is_featured' => true,
                'is_rajuk_approved' => true,
                'is_verified' => true,
                'has_open_house' => true,
                'latitude' => 23.7785,
                'longitude' => 90.4172,
                'agent_id' => $agent1?->id,
                'images' => [
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200&auto=format&fit=crop',
                ],
                'amenities' => [
                    '15 Katha South-Facing Freehold Land',
                    '2-Storey Existing Structure / Redevelopment Ready',
                    'Wide Gulshan-1 Frontage Road Access',
                    'Independent Boundary Demarcated',
                    'Full Owner Physical Possession',
                    'WASA Water, DESCO Electricity & Gas Connection',
                    'Bank Escrow Transaction Support',
                    'RAJUK Sale Permission Assistance',
                ],
                'documents_verified' => [
                    'মালিকানা দলিল ও ওয়ারিশান সনদপত্র (Inheritance Deed)',
                    '২০২৩ সালের নামজারি ও জমাভাগ খতিয়ান (Updated Mutation)',
                    'বাংলা ১৪৩২ সনের অনলাইন ভূমি উন্নয়ন কর/খাজনা রশিদ',
                    'নিষ্কণ্টক মালিকানা সনদ (Clear Title Certificate)',
                    'সার্ভিস চার্জ ও ডকুমেন্টেশন ফি পরিশোধ রশিদ',
                    'অপ্রত্যাহারযোগ্য পাওয়ার অব অ্যাটর্নি (গনিউর রাহমান গং)',
                ],
                'buyer_details' => [
                    'landUse' => 'Residential',
                    'cornerPlot' => 'No',
                    'roadWidth' => 40,
                    'buildingDescription' => '১৫ কাঠা জমির উপর ২ তলা পুরাতন দালান/ভবন বিদ্যমান। নতুন বহুতল ভবন নির্মাণের উপযোগী।',
                    'utilities' => 'বিদ্যুৎ, গ্যাস ও ওয়াসা পানি সংযোগ হালনাগাদ রয়েছে।',
                    'priceBasis' => 'Total',
                    'negotiable' => 'Yes',
                    'priceIncludes' => '১৫ কাঠা জমি এবং বিদ্যমান ২ তলা ভবন সহ মোট মূল্য।',
                    'depositPercent' => 25,
                    'agreementDuration' => 'চুক্তির তারিখ হতে ৯০ দিন',
                    'paymentSchedule' => 'বায়না ২৫%, অবশিষ্ট মূল্য রাজউক অনুমতি সাপেক্ষে ব্যাংক পে-অর্ডারে হস্তান্তরকালে।',
                    'paymentMethod' => 'ব্যাংক পে-অর্ডার / একাউন্ট ট্রান্সফার',
                    'registrationCost' => 'সরকারি বিধি মোতাবেক সকল রেজিস্ট্রেশন ফি ক্রেতা বহন করবেন।',
                    'buyerCosts' => 'ক্রেতা নিজ দায়িত্বে রেজিস্ট্রেশন ও সংশ্লিষ্ট সরকারি ফি নির্বাহ করবেন।',
                    'sellerCosts' => 'সার্ভিস চার্জ ও ডকুমেন্টেশন ফি পরিশোধ সম্পন্ন।',
                    'transferTimeline' => 'রাজউক থেকে বিক্রয়ের অনুমতি প্রাপ্তির ১৫ কার্যদিবসের মধ্যে।',
                    'transferTrigger' => 'রাজউক কর্তৃক বিক্রয় অনুমতি পত্র জারির দিন থেকে।',
                    'ownerCount' => 5,
                    'ownershipSource' => 'Inheritance',
                    'possession' => 'Owner',
                    'bankLoan' => 'None declared',
                    'existingAgreement' => 'None declared',
                    'saleAuthority' => 'গনিউর রাহমান গং (অপ্রত্যাহারযোগ্য পাওয়ার অব অ্যাটর্নি বলে)',
                    'ownershipNotes' => 'ওয়ারিশ সূত্রে ৫ জন মালিক, কোনো বিরোধ নেই, সম্পূর্ণ নিষ্কণ্টক জমি।',
                    'mutationStatus' => 'Available',
                    'taxPaidThrough' => 'বাংলা ১৪৩২ সন',
                    'serviceChargeStatus' => 'জমা দেওয়া আছে',
                    'approvalDetails' => 'রেসিডেন্সিয়াল জোন হিসেবে অনুমোদিত, রাজউক থেকে বিক্রয় অনুমতি প্রক্রিয়া চলমান।',
                    'documentSummary' => 'নিষ্কণ্টক / টোটাল কাগজ-পাতি ১০০% আপডেট।',
                    'sourceDate' => '2026-09-15',
                    'updatedOn' => '2026-09-15',
                ],
            ]
        );

        // 2. Gulshan-2 Road 92 Plot 06 Estate
        Property::updateOrCreate(
            ['slug' => 'gulshan-2-road-92-plot-06-17-katha-building'],
            [
                'title' => 'গুলশান ২, রোড ৯২, প্লট ০৬ — ১৭.১৮ কাঠা জমি ও ২ তলা বিল্ডিং',
                'slug' => 'gulshan-2-road-92-plot-06-17-katha-building',
                'tagline' => '১৭.১৮ কাঠা রেসিডেন্সিয়াল জমি ও ২ তলা বিল্ডিং | প্রতি কাঠা ৭ কোটি (আলোচনা সাপেক্ষ)',
                'description' => 'গুলশান ২, রোড নম্বর ৯২, প্লট ০৬ এ ১৭.১৮ কাঠা জমি ও ২ তলা বিল্ডিং বিক্রয়ের প্রস্তাব। পৈতৃক সূত্রে ২ জন ভাই জমির বর্তমান মালিক। বাংলা ১৪৩২ সনের অনলাইন খাজনা পরিশোধ করা আছে, সার্ভিস চার্জ ও ডকুমেন্টেশন ফি জমা দেওয়া আছে। রেসিডেন্সিয়াল অনুমোদনপ্রাপ্ত। নিষ্কণ্টক ও টোটাল কাগজ-পাতি আপডেট কমপ্লিট। জমি ও দখল সম্পূর্ণ নিজ অধীনে। বিক্রিত মূল্যের ৩০% বায়না। আর্থিক লেনদেন ব্যাংকের মাধ্যমে। রাজউক থেকে বিক্রয়ের অনুমতি প্রাপ্তি ১৫ (পনের) কার্যদিবস। বিক্রয় অনুমতি পত্র ও সার্ভিস চার্জ বিক্রেতা বহন করবেন।',
                'address' => 'রোড ৯২, প্লট ০৬, গুলশান-২, ঢাকা-১২১২',
                'city' => 'Dhaka',
                'state' => 'Dhaka North',
                'area_name' => 'Gulshan-2',
                'price' => 1202600000,
                'price_unit' => 'প্রতি কাঠা ৳ ৭.০০ কোটি (আলোচনা সাপেক্ষ)',
                'listing_type' => 'Sale',
                'property_type' => 'Land',
                'status' => 'Active',
                'bedrooms' => 8,
                'bathrooms' => 8,
                'balconies' => 6,
                'square_footage' => 6800,
                'land_size' => 17.18,
                'land_unit' => 'Katha',
                'parking' => 8,
                'floor_number' => 1,
                'total_floors' => 2,
                'facing' => 'South',
                'completion_status' => 'Ready',
                'year_built' => 2005,
                'is_featured' => true,
                'is_rajuk_approved' => true,
                'is_verified' => true,
                'has_open_house' => true,
                'latitude' => 23.7962,
                'longitude' => 90.4195,
                'agent_id' => $agent2?->id,
                'images' => [
                    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
                ],
                'amenities' => [
                    '17.18 Katha Prime Gulshan-2 Diplomatic Vicinity',
                    'Road 92 Wide Avenue Frontage',
                    '2-Storey Modern Residential Structure',
                    'Direct Self-Possession by 2 Brothers',
                    'Zero Encumbrance or Bank Liability',
                    'Gas, Electricity & Deep WASA Connection',
                    'Pre-vetted Title Deeds & Survey Khatian',
                    'Seller Bears RAJUK Permission & Service Charge',
                ],
                'documents_verified' => [
                    'পৈতৃক সূত্রের মূল মালিকানা দলিল (Paternal Title Deed)',
                    'অনলাইন নামজারি ও ডিসিআর পর্চা (Mutation DCR)',
                    'বাংলা ১৪৩২ সনের হালনাগাদ অনলাইন খাজনা রশিদ',
                    'রাজউক অনুমোদিত আবাসিক প্লট রেকর্ড',
                    'নিষ্কণ্টক মালিকানা ও দাগ খতিয়ান যাচাইকৃত',
                ],
                'buyer_details' => [
                    'landUse' => 'Residential',
                    'cornerPlot' => 'No',
                    'roadWidth' => 50,
                    'buildingDescription' => '১৭.১৮ কাঠা জমিতে ২ তলা আবাসিক ভবন। সুদৃশ্য বাগান ও ড্রাইভওয়ে সহ।',
                    'utilities' => 'গ্যাস, থ্রি-ফেজ বিদ্যুৎ ও ওয়াসা পানির লাইন সার্বক্ষণিক চালু।',
                    'priceBasis' => 'Per land unit',
                    'negotiable' => 'Yes',
                    'priceIncludes' => 'প্রতি কাঠা ৭ কোটি টাকা হিসেবে মোট ১৭.১৮ কাঠা জমি ও বিদ্যমান ২ তলা বিল্ডিং (মোট মূল্য ৳ ১২০.২৬ কোটি আলোচনা সাপেক্ষ)।',
                    'depositPercent' => 30,
                    'agreementDuration' => 'চুক্তির তারিখ হতে ৯০-১২০ কার্যদিবস',
                    'paymentSchedule' => 'বায়না ৩০%, অবশিষ্ট মূল্য রাজউক বিক্রয় অনুমতি প্রাপ্তির পর রেজিস্ট্রি সম্পন্নকালে।',
                    'paymentMethod' => 'ব্যাংক ড্রাফট / পে-অর্ডার / আরটিজিএস',
                    'registrationCost' => 'রেজিস্ট্রেশন ফি ও সরকারি কর ক্রেতার নিয়ম অনুযায়ী।',
                    'buyerCosts' => 'রেজিস্ট্রেশন খরচ ও কর ক্রেতা বহন করবেন।',
                    'sellerCosts' => 'বিক্রয় অনুমতি পত্র ও সার্ভিস চার্জ বিক্রেতা বহন করবেন।',
                    'transferTimeline' => 'রাজউক থেকে বিক্রয়ের অনুমতি প্রাপ্তির ১৫ কার্যদিবসের মধ্যে।',
                    'transferTrigger' => 'রাজউক বিক্রয় অনুমতি পত্র হাতে পাওয়ার পর।',
                    'ownerCount' => 2,
                    'ownershipSource' => 'Inheritance',
                    'possession' => 'Owner',
                    'bankLoan' => 'None declared',
                    'existingAgreement' => 'None declared',
                    'saleAuthority' => 'নিজ (২ জন ভাই যৌথভাবে উপস্থিত থেকে দলিল সম্পাদন করবেন)',
                    'ownershipNotes' => 'পৈতৃক সূত্রে ২ ভাই একক মালিক, কোনো তৃতীয় পক্ষের দাবি বা মামলা নেই।',
                    'mutationStatus' => 'Available',
                    'taxPaidThrough' => 'বাংলা ১৪৩২ সন',
                    'serviceChargeStatus' => 'পরিশোধিত ও জমা আছে',
                    'approvalDetails' => 'গুলশান-২ আবাসিক এলাকা, রাজউক বিক্রয় অনুমতি বিক্রেতা নিজ খরচে নিবেন।',
                    'documentSummary' => 'নিষ্কণ্টক / টোটাল কাগজ-পাতি আপডেট কমপ্লিট।',
                    'sourceDate' => '2026-09-14',
                    'updatedOn' => '2026-09-14',
                ],
            ]
        );

        // 3. Gulshan-2 Road 48/4B Commercial Corner Plot
        Property::updateOrCreate(
            ['slug' => 'gulshan-2-road-48-4b-31-katha-commercial-corner-plot'],
            [
                'title' => 'গুলশান-২, রোড ৪৮/৪বি — ৩১ কাঠা বাণিজ্যিক কর্নার প্লট ও ২ তলা দালান',
                'slug' => 'gulshan-2-road-48-4b-31-katha-commercial-corner-plot',
                'tagline' => '৩১ কাঠা বাণিজ্যিক কর্নার প্লট ও ২ তলা দালান | প্রতি কাঠা ১৪ কোটি (আলোচনা সাপেক্ষ)',
                'description' => 'গুলশান-২, রোড ৪৮/৪বি তে ৩১ কাঠা বাণিজ্যিক কর্নার প্লট ও ২ তলা দালান বিক্রয়ের প্রস্তাব। ওয়ারিশ সূত্রে ৩ জন বর্তমান মালিক এবং নামজারি সম্পন্ন আছে। কমার্শিয়াল অনুমোদনপ্রাপ্ত। বাংলা ১৪৩২ সনের অনলাইন খাজনা পরিশোধিত ও সার্ভিস চার্জ জমা আছে। নিষ্কণ্টক ও টোটাল কাগজ-পাতি আপডেট কমপ্লিট। জমির দখল মালিকের। বিক্রিত মূল্যের ৩০% বায়না। আর্থিক লেনদেন ব্যাংকের মাধ্যমে। রাজউক থেকে বিক্রয়ের অনুমতি প্রাপ্তি ১৫ (পনের) কার্যদিবস। বিক্রয় অনুমতি পত্র ও সার্ভিস চার্জ বিক্রেতা বহন করবেন।',
                'address' => 'রোড ৪৮/৪বি, গুলশান-২, ঢাকা-১২১২',
                'city' => 'Dhaka',
                'state' => 'Dhaka North',
                'area_name' => 'Gulshan-2',
                'price' => 4340000000,
                'price_unit' => 'প্রতি কাঠা ৳ ১৪.০০ কোটি (আলোচনা সাপেক্ষ)',
                'listing_type' => 'Sale',
                'property_type' => 'Commercial',
                'status' => 'Active',
                'bedrooms' => 10,
                'bathrooms' => 10,
                'balconies' => 6,
                'square_footage' => 12000,
                'land_size' => 31.0,
                'land_unit' => 'Katha',
                'parking' => 20,
                'floor_number' => 1,
                'total_floors' => 2,
                'facing' => 'South-East',
                'completion_status' => 'Ready',
                'year_built' => 2002,
                'is_featured' => true,
                'is_rajuk_approved' => true,
                'is_verified' => true,
                'has_open_house' => true,
                'latitude' => 23.7915,
                'longitude' => 90.4138,
                'agent_id' => $agent3?->id,
                'images' => [
                    'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1577495508048-b635879837f1?q=80&w=1200&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
                ],
                'amenities' => [
                    '31 Katha Commercial Approved Corner Plot',
                    'Double Road Corner Frontage with High Visibility',
                    'Suitable for 25+ Storey Corporate Headquarters / Luxury Mixed Tower',
                    'Existing 2-Storey Concrete Building',
                    'High-Tension Power Substation & Commercial Utility Line',
                    'Dispute-Free Inheritance Title with Updated Namjari',
                    'Seller Bears RAJUK Permission & Service Charge',
                    'Direct Owner Possession',
                ],
                'documents_verified' => [
                    'মালিকানা দলিল ও ওয়ারিশান সনদ (Inheritance Title & Succession)',
                    'অনুমোদিত নামজারি ও জমাভাগ খতিয়ান (Completed Mutation)',
                    'বাংলা ১৪৩২ সনের অনলাইন খাজনা পরিশোধ রশিদ',
                    'কমার্শিয়াল ব্যবহারের সরকারি অনুমোদন সনদ',
                    'সার্ভিস চার্জ ও ডকুমেন্টেশন ফি জমা রশিদ',
                    'নিষ্কণ্টক ও নির্ভেজাল টাইটেল রিপোর্ট (Clear Title Audit)',
                ],
                'buyer_details' => [
                    'landUse' => 'Commercial',
                    'cornerPlot' => 'Yes',
                    'roadWidth' => 80,
                    'buildingDescription' => '৩১ কাঠা কর্নার প্লটে ২ তলা দালান বিদ্যমান। মাল্টি-স্টোরি কমার্শিয়াল টাওয়ার নির্মাণের জন্য আদর্শ।',
                    'utilities' => 'বাণিজ্যিক বিদ্যুৎ, গ্যাস ও উচ্চ ক্ষমতাসম্পন্ন ওয়াসা লাইন।',
                    'priceBasis' => 'Per land unit',
                    'negotiable' => 'Yes',
                    'priceIncludes' => 'প্রতি কাঠা ১৪ কোটি টাকা হিসেবে মোট ৩১ কাঠা বাণিজ্যিক কর্নার প্লট ও বিদ্যমান ২ তলা দালান (মোট মূল্য ৳ ৪৩৪.০০ কোটি আলোচনা সাপেক্ষ)।',
                    'depositPercent' => 30,
                    'agreementDuration' => 'চুক্তির পর ১২০ কার্যদিবস',
                    'paymentSchedule' => 'বায়না ৩০%, অবশিষ্ট ৭০% রাজউক বিক্রয় অনুমতি সম্পন্ন হওয়ার পর রেজিস্ট্রি কালে ব্যাংকের মাধ্যমে।',
                    'paymentMethod' => 'ব্যাংক পে-অর্ডার / আরটিজিএস',
                    'registrationCost' => 'সরকারি কমার্শিয়াল রেজিস্ট্রেশন কর ক্রেতার নিজ দায়িত্বে।',
                    'buyerCosts' => 'রেজিস্ট্রেশন ফি ও অন্যান্য সরকারি শুল্ক ক্রেতা বহন করবেন।',
                    'sellerCosts' => 'বিক্রয় অনুমতি পত্র ও সার্ভিস চার্জ বিক্রেতা বহন করবেন।',
                    'transferTimeline' => 'রাজউক থেকে বিক্রয়ের অনুমতি প্রাপ্তির ১৫ কার্যদিবসের মধ্যে।',
                    'transferTrigger' => 'রাজউক বিক্রয় অনুমতি পত্র প্রকাশের পর।',
                    'ownerCount' => 3,
                    'ownershipSource' => 'Inheritance',
                    'possession' => 'Owner',
                    'bankLoan' => 'None declared',
                    'existingAgreement' => 'None declared',
                    'saleAuthority' => 'ওয়ারিশান ৩ জন মালিক যৌথভাবে',
                    'ownershipNotes' => 'ওয়ারিশ সূত্রে নামজারি সম্পন্ন, ৩ জন মালিকের কোনো বিরোধ নেই।',
                    'mutationStatus' => 'Available',
                    'taxPaidThrough' => 'বাংলা ১৪৩২ সন',
                    'serviceChargeStatus' => 'জমা দেওয়া আছে',
                    'approvalDetails' => 'কমার্শিয়াল অনুমোদন প্রাপ্ত, রাজউক বিক্রয় অনুমতি বিক্রেতা সম্পন্ন করে দিবেন।',
                    'documentSummary' => 'নিষ্কণ্টক / টোটাল কাগজ-পাতি আপডেট কমপ্লিট।',
                    'sourceDate' => '2026-09-15',
                    'updatedOn' => '2026-09-15',
                ],
            ]
        );

        // 4. Lake View 23 Katha Edifice
        Property::updateOrCreate(
            ['slug' => 'lake-view-gulshan-1-road-8-23-katha-building'],
            [
                'title' => 'লেক ভিউ — গুলশান-১ রোড ৮, বাড়ি ১০ এ ২৩ কাঠা জমিতে ৬ তলা বাণিজ্যিক ভবন',
                'slug' => 'lake-view-gulshan-1-road-8-23-katha-building',
                'tagline' => 'লেক ভিউ | ২৩ কাঠা জমিতে ৬ তলা ভবন ও ২৮টি কার পার্কিং | মূল্য ১৩৫ কোটি (আলোচনা সাপেক্ষ)',
                'description' => 'লেক ভিউ — বাড়ি #১০, রোড #৮, গুলশান-১, ঢাকা এ অবস্থিত ২৩ কাঠা জমির উপর ৬ তলা বিশিষ্ট সুদৃশ্য ভবন। ইউটিলিটি সরবরাহ সম্পূর্ণ আপডেটেড এবং ২৮টি কার পার্কিং সুবিধা রয়েছে। বর্তমান মালিক ২ জন (মূল মালিক মোঃ তওফিকুল ইসলাম)। জমি মালিকের সরাসরি দখলে এবং নামজারি ও খাজনা পরিশোধিত। সম্পূর্ণ নিষ্কণ্টক ও টোটাল কাগজ-পাতি আপডেট কমপ্লিট। কোনো ব্যাংক লোন নেই। বিক্রিত মূল্যের ৩০% বায়না। রাজউক থেকে বিক্রয়ের অনুমতি প্রাপ্তি ১৫ কার্যদিবস। ৩০০ টাকার নন-জুডিশিয়াল স্ট্যাম্পে হস্তান্তর চুক্তি সম্পন্ন হবে।',
                'address' => 'বাড়ি ১০, রোড ৮, গুলশান-১, ঢাকা-১২১২',
                'city' => 'Dhaka',
                'state' => 'Dhaka North',
                'area_name' => 'Gulshan-1',
                'price' => 1350000000,
                'price_unit' => 'মোট মূল্য ৳ ১৩৫ কোটি (আলোচনা সাপেক্ষে কম হতে পারে)',
                'listing_type' => 'Sale',
                'property_type' => 'Duplex',
                'status' => 'Active',
                'bedrooms' => 16,
                'bathrooms' => 18,
                'balconies' => 12,
                'square_footage' => 26000,
                'land_size' => 23.0,
                'land_unit' => 'Katha',
                'parking' => 28,
                'floor_number' => 1,
                'total_floors' => 6,
                'facing' => 'South',
                'completion_status' => 'Ready',
                'year_built' => 2018,
                'is_featured' => true,
                'is_rajuk_approved' => true,
                'is_verified' => true,
                'has_open_house' => true,
                'latitude' => 23.7798,
                'longitude' => 90.4148,
                'agent_id' => $agent1?->id,
                'images' => [
                    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop',
                ],
                'amenities' => [
                    '23 Katha Lakeside Prime Land in Gulshan-1',
                    '6-Storey Modern Completed Architectural Edifice',
                    '28 Dedicated Covered Car Parking Bays',
                    'Independent 500KVA Substation & Full Generator Backup',
                    'High-Speed Dual Passenger Elevators',
                    'Direct Lake View and Expansive Terrace Gardens',
                    'Owner Physical Possession with 24/7 Security Post',
                    'Comprehensive Utility Supply 100% Updated',
                ],
                'documents_verified' => [
                    'মূল নিষ্কণ্টক স্বত্ব দলিল ও বণ্টননামা (Freehold Title Deed)',
                    'হালনাগাদ নামজারি পর্চা ও জমাভাগ রেকর্ড (Updated Mutation)',
                    'অনলাইন ভূমি উন্নয়ন কর ও খাজনা পরিশোধ রশিদ',
                    'রাজউক অনুমোদিত ৬ তলা ভবনের স্থাপত্য ও কাঠামোগত নকশা',
                    'ফায়ার সার্ভিস ও পরিবেশ ছাড়পত্র সনদ',
                    '৩০০ টাকার নন-জুডিশিয়াল স্ট্যাম্পে কার্যকারী চুক্তিপত্র প্রস্তুত',
                ],
                'buyer_details' => [
                    'landUse' => 'Residential',
                    'cornerPlot' => 'No',
                    'roadWidth' => 60,
                    'buildingDescription' => 'লেক ভিউ: ২৩ কাঠা জমিতে ৬ তলা বিশিষ্ট আধুনিক ভবন। কার পার্কিং সংখ্যা ২৮টি।',
                    'utilities' => 'ইউটিলিটি সরবরাহ সম্পূর্ণ আপডেট—বিদ্যুৎ সাবস্টেশন, গ্যাস সংযোগ ও গভীর নলকূপ ওয়াসা।',
                    'priceBasis' => 'Total',
                    'negotiable' => 'Yes',
                    'priceIncludes' => '২৩ কাঠা জমি, ৬ তলা সম্পূর্ণ ভবন ও ২৮টি কার পার্কিং সহ মোট মূল্য ১৩৫ কোটি টাকা (আলোচনা সাপেক্ষে কম হতে পারে)।',
                    'depositPercent' => 30,
                    'agreementDuration' => 'চুক্তির তারিখ হতে ৯০ দিন',
                    'paymentSchedule' => 'বায়না ৩০%, কার্যকারী পেমেন্ট শিডিউল ৩০০ টাকার নন-জুডিশিয়াল স্ট্যাম্পের মাধ্যমে চুক্তি সাপেক্ষে।',
                    'paymentMethod' => 'ব্যাংক ড্রাফট / পে-অর্ডারের মাধ্যমে',
                    'registrationCost' => 'ক্রেতা নিজ দায়িত্বে রেজিস্ট্রেশন সম্পন্ন করবেন।',
                    'buyerCosts' => 'ক্রেতা নিজ দায়িত্বে রেজিস্ট্রেশন ও হস্তান্তরের খরচ করবেন।',
                    'sellerCosts' => 'সার্ভিস চার্জ ও রাজউক অনুমতি প্রক্রিয়াকরণ।',
                    'transferTimeline' => 'রাজউক থেকে বিক্রয়ের অনুমতি প্রাপ্তি ১৫ (পনের) কার্যদিবস।',
                    'transferTrigger' => 'রাজউক অনুমোদন ও যৌথ চুক্তি সম্পাদনের পর।',
                    'ownerCount' => 2,
                    'ownershipSource' => 'Purchase',
                    'possession' => 'Owner',
                    'bankLoan' => 'None declared',
                    'existingAgreement' => 'None declared',
                    'saleAuthority' => 'মালিক মোঃ তওফিকুল ইসলাম (প্রতিনিধি: মোঃ আবু হানিফ)',
                    'ownershipNotes' => 'মালিক ২ জন, কোনো ব্যাংক লোন বা আইনি ঝামেলা নেই, সম্পূর্ণ নিষ্কণ্টক।',
                    'mutationStatus' => 'Available',
                    'taxPaidThrough' => 'হালনাগাদ (নামজারি ও খাজনা পরিশোধ করা আছে)',
                    'serviceChargeStatus' => 'আপডেট আছে',
                    'approvalDetails' => 'রাজউক অনুমোদিত ভবন, বিক্রয়ের অনুমতি প্রাপ্তি ১৫ কার্যদিবসের মধ্যে।',
                    'documentSummary' => 'নিষ্কণ্টক / টোটাল কাগজ-পাতি আপডেট কমপ্লিট।',
                    'sourceDate' => '2026-09-15',
                    'updatedOn' => '2026-09-15',
                ],
            ]
        );

        // 5. Dhaur Kamarpara 8.5 Katha B+G+9 Land Share Project
        Property::updateOrCreate(
            ['slug' => 'dhaur-kamarpara-8-5-katha-b-g-9-land-share'],
            [
                'title' => 'ধউর, কামারপাড়া — ৮.৫ কাঠা জমিতে রাজউক প্রস্তাবিত B+G+9 ভবনের জমির শেয়ার',
                'slug' => 'dhaur-kamarpara-8-5-katha-b-g-9-land-share',
                'tagline' => '৮.৫ কাঠা জমি | রাজউক প্রস্তাবিত B+G+9 প্ল্যান পাস | ১২৫০ বর্গফুট ফ্ল্যাট | প্রতি শেয়ার ৳ ২২ লাখ',
                'description' => "সীমিত সংখ্যক জমির শেয়ার বিক্রয় হবে।\nজমির পরিমাণ : ৮.৫ কাঠা।\nরাজউক প্রস্তাবিত প্ল্যান পাস B+G+9 (বেজমেন্ট + গ্রাউন্ড + ৯ তলা)।\nমোট ফ্ল্যাটের সংখ্যা : ৩৬ টি।\nপ্রতি ফ্লোরে ফ্ল্যাটের সংখ্যা : ৪ টি।\nফ্ল্যাটের আয়তন : ১২৫০ বর্গফুট।\nপ্রতি ইউনিটে : ৩ টি বেড রুম, ৩ টি বাথরুম, ৩ টি বারান্দা, ড্রয়িং, ডাইনিং ও রান্নাঘর।\nলিফট : ১ টি।\nসিঁড়ি : ১টি।\nসাব - স্টেশন : ১ টি।\nবেজমেন্ট + গ্রাউন্ড ফ্লোর পার্কিং।\nপ্রতি ইউনিটে থাকবে ইন্টারনেট, ডিশ ও ইন্টারকম সহ সকল আধুনিক সুযোগ সুবিধা।\nছাদের উপর কমিউনিটি রুম বা অফিস ও বাচ্চাদের খেলাধুলার ওপেন স্পেস।\nনির্মাণ শেষে সিসি টিভি ক্যামেরা ও নিরাপত্তা কর্মী দ্বারা সার্বক্ষণিক নিরাপত্তার ব্যবস্থা রাখা হবে।\n\nজমির লোকেশন :\nধউর, গোলগোলার মোড়, ওয়ালটন প্লাজার রোডে। কামারপাড়া - দিয়াবাড়ী মেইন রোডের ১০০ ফুট ভিতরে ২১ ফুট প্রশস্ত পাকা রাস্তার পাশে জমির অবস্থান।\n\nআশেপাশের সুযোগ-সুবিধা ও যোগাযোগ :\nজমির আশেপাশে বাজার, স্কুল কলেজ, মসজিদ, মাদ্রাসা ও অন্যান্য শিক্ষা প্রতিষ্ঠান আছে। কামারপাড়া বাস স্ট্যান্ড, ধউর বাস স্টেশন, আহসানিয়া ক্যান্সার হাসপাতাল, ইস্ট ওয়েস্ট মেডিকেল, শিপ মেডিকেল, কামারপাড়া হাই স্কুল এন্ড কলেজ, মাইলস্টোন কলেজ ইত্যাদি প্রতিষ্ঠান গুলো ৫০০ মিটার থেকে ১ কিমি মধ্যে অবস্থিত।",
                'address' => 'ধউর, গোলগোলার মোড়, ওয়ালটন প্লাজার রোড, কামারপাড়া, উত্তরা, ঢাকা',
                'city' => 'Dhaka',
                'state' => 'Dhaka North',
                'area_name' => 'Uttara / Kamarpara',
                'price' => 2200000,
                'price_unit' => 'প্রতি শেয়ার ৳ ২২ লাখ',
                'hide_price' => false,
                'listing_type' => 'Sale',
                'property_type' => 'Land Share',
                'status' => 'Active',
                'bedrooms' => 3,
                'bathrooms' => 3,
                'balconies' => 3,
                'square_footage' => 1250,
                'land_size' => 8.5,
                'land_unit' => 'Katha',
                'parking' => 36,
                'floor_number' => 1,
                'total_floors' => 10,
                'facing' => 'East',
                'completion_status' => 'Upcoming',
                'year_built' => 2026,
                'is_featured' => true,
                'is_rajuk_approved' => true,
                'is_verified' => true,
                'has_open_house' => true,
                'latitude' => 23.8967,
                'longitude' => 90.3752,
                'agent_id' => $agent1?->id,
                'images' => [
                    '/img/properties/dhaur-kamarpara-8-5-katha-building.jpg',
                    '/img/properties/dhaur-kamarpara-8-5-katha-map.png',
                    '/img/properties/dhaur-kamarpara-1250-sqft-floorplan.jpg',
                ],
                'amenities' => [
                    '৮.৫ কাঠা জমির শেয়ার (মোট ৩৬টি শেয়ার)',
                    'রাজউক প্রস্তাবিত প্ল্যান পাস B+G+9 (বেজমেন্ট + গ্রাউন্ড + ৯ তলা)',
                    '১২৫০ বর্গফুটের আধুনিক ফ্ল্যাট (৩ বেড, ৩ বাথ, ৩ বারান্দা)',
                    'ড্রয়িং, ডাইনিং ও সুপরিসর রান্নাঘর',
                    'বেজমেন্ট ও গ্রাউন্ড ফ্লোর কার পার্কিং',
                    'আধুনিক হাই-স্পিড প্যাসেঞ্জার লিফট (১টি)',
                    'প্রশস্ত জরুরি অগ্নিনির্বাপক সিঁড়ি (১টি)',
                    'নিজস্ব বৈদ্যুতিক সাব-স্টেশন (১টি)',
                    'ইন্টারনেট, ডিশ ও ইন্টারকম সংযোগ সুবিধা',
                    'ছাদের উপর কমিউনিটি রুম / অফিস স্পেস',
                    'বাচ্চাদের খেলাধুলার জন্য রুফটপ ওপেন স্পেস',
                    'সিসিটিভি ক্যামেরা ও সার্বক্ষণিক নিরাপত্তা কর্মী',
                    '২১ ফুট প্রশস্ত পাকা রাস্তার সাথে সংযোগ',
                    'কামারপাড়া-দিয়াবাড়ী মেইন রোডের ১০০ ফুট ভেতরে',
                    'মেট্রোরেল উত্তরা উত্তর স্টেশন ও মাইলস্টোন কলেজ সন্নিকটে',
                ],
                'documents_verified' => [
                    'জমির মূল মালিকানা দলিল ও বায়া দলিল (CS, SA, RS, BS)',
                    'হালনাগাদ নামজারি ও জমাভাগ খতিয়ান (Updated Mutation)',
                    'অনলাইন ভূমি উন্নয়ন কর ও খাজনা হালনাগাদ রশিদ',
                    'রাজউক প্রস্তাবিত প্ল্যান পাস অনুমোদন নথি (B+G+9 Proposed Plan)',
                    'জমির সীমানা চিহ্নিতকরণ ও লোকেশন লেআউট ম্যাপ',
                    'নিষ্কণ্টক মালিকানা প্রত্যয়ন (Clear Title Certificate)',
                ],
                'buyer_details' => [
                    'landUse' => 'Residential',
                    'cornerPlot' => 'No',
                    'roadWidth' => 21,
                    'shareCount' => 36,
                    'shareLandSize' => 0.236,
                    'buildingDescription' => '৮.৫ কাঠা জমিতে রাজউক প্রস্তাবিত প্ল্যান পাস B+G+9 বিশিষ্ট ৩৬টি আধুনিক ফ্ল্যাট সম্বলিত প্রকল্প।',
                    'utilities' => 'ইন্টারনেট, ডিশ, ইন্টারকম, নিজস্ব বৈদ্যুতিক সাব-স্টেশন ও অগ্নিনির্বাপক সিঁড়ি সুবিধা।',
                    'parkingDetails' => 'বেজমেন্ট ও গ্রাউন্ড ফ্লোরে সুপরিসর কার পার্কিং।',
                    'securityDetails' => 'সিসিটিভি ক্যামেরা ও সার্বক্ষণিক নিরাপত্তা কর্মী।',
                    'rooftopDetails' => 'ছাদের উপর কমিউনিটি রুম বা অফিস ও বাচ্চাদের খেলাধুলার উন্মুক্ত ওপেন স্পেস।',
                    'priceBasis' => 'Per share',
                    'negotiable' => 'Yes',
                    'depositPercent' => 20,
                    'agreementDuration' => 'পারস্পরিক চুক্তি মোতাবেক',
                    'paymentMethod' => 'ব্যাংক চেক / পে-অর্ডার / অনলাইন ট্রান্সফার',
                    'registrationCost' => 'সরকারি বিধি মোতাবেক প্রযোজ্য রেজিস্ট্রেশন ফি ক্রেতা বহন করবেন।',
                    'transferTimeline' => 'চুক্তি ও শর্তাবলী অনুযায়ী নির্ধারিত সময়ে শেয়ার ও দখল হস্তান্তর।',
                    'possession' => 'Developer & Share Holders Joint Execution',
                    'approvalDetails' => 'রাজউক প্রস্তাবিত প্ল্যান পাস B+G+9 (বেজমেন্ট + গ্রাউন্ড + ৯ তলা)।',
                    'documentSummary' => 'নিষ্কণ্টক মালিকানা ও হালনাগাদ কাগজপত্র।',
                    'sourceDate' => '2026-09-28',
                    'updatedOn' => '2026-09-28',
                ],
            ]
        );

        LaunchListings::correct();
        LaunchListings::rewriteCopy();
    }
}
